# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModelView.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModelView(object):
    def setupUi(self, ModelView):
        ModelView.setObjectName("ModelView")
        ModelView.resize(366, 617)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(False)
        font.setWeight(50)
        ModelView.setFont(font)
        ModelView.setAutoFillBackground(False)
        ModelView.setStyleSheet("background-color: rgb(71, 52, 209);\n"
"")
        ModelView.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(ModelView)
        self.centralwidget.setObjectName("centralwidget")
        self.Id1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Id1.setGeometry(QtCore.QRect(10, 60, 341, 22))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Id1.setFont(font)
        self.Id1.setStyleSheet("background-color: white;\n"
"border-radius: 10px;")
        self.Id1.setText("")
        self.Id1.setObjectName("Id1")
        self.Id2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Id2.setGeometry(QtCore.QRect(10, 90, 341, 22))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Id2.setFont(font)
        self.Id2.setStyleSheet("background-color: white;\n"
"border-radius: 10px;")
        self.Id2.setText("")
        self.Id2.setObjectName("Id2")
        self.predictButton = QtWidgets.QPushButton(self.centralwidget)
        self.predictButton.setGeometry(QtCore.QRect(100, 130, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.predictButton.setFont(font)
        self.predictButton.setStyleSheet("background-color: white;\n"
"border-radius: 10px;")
        self.predictButton.setObjectName("predictButton")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(50, 20, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color: rgb(255, 255, 255);")
        self.Title.setObjectName("Title")
        self.Prediction = QtWidgets.QLabel(self.centralwidget)
        self.Prediction.setGeometry(QtCore.QRect(20, 180, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Prediction.setFont(font)
        self.Prediction.setStyleSheet("color: rgb(255, 255, 255)")
        self.Prediction.setObjectName("Prediction")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 270, 321, 331))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.Prediction.raise_()
        self.Id1.raise_()
        self.Id2.raise_()
        self.predictButton.raise_()
        self.Title.raise_()
        self.label.raise_()
        ModelView.setCentralWidget(self.centralwidget)

        self.retranslateUi(ModelView)
        QtCore.QMetaObject.connectSlotsByName(ModelView)

    def retranslateUi(self, ModelView):
        _translate = QtCore.QCoreApplication.translate
        ModelView.setWindowTitle(_translate("ModelView", "MainWindow"))
        self.Id1.setPlaceholderText(_translate("ModelView", "Input ID..."))
        self.Id2.setPlaceholderText(_translate("ModelView", "Input ID..."))
        self.predictButton.setText(_translate("ModelView", "Make Prediction"))
        self.Title.setText(_translate("ModelView", "3D GCN Predictive Model"))
        self.Prediction.setText(_translate("ModelView", "Prediction Text"))
        self.label.setText(_translate("ModelView", "Feature Weights"))
